name: rmc
title: rmc
url: https://randommeaninglesscharacters.com
shopurl: https://shop.randommeaninglesscharacters.com
imgurl: https://cdn.randommeaninglesscharacters.com/img-dsi/
appurl: https://cdn.randommeaninglesscharacters.com/rmc-prg/
releaseurl: https://cdn.randommeaninglesscharacters.com/assets-dsi/release/
releaseurl_alt: https://cdn.randommeaninglesscharacters.com/releases/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
feed:
  posts_limit: 20