name: rmc
title: rmc
url: https://randommeaninglesscharacters.com
target: whatever # set to "STRIPPED" for no links version (also unlisted to google)
shopurl: https://shop.randommeaninglesscharacters.com
imgurl: https://cdn.randommeaninglesscharacters.com/img-dsi/
appurl: https://cdn.randommeaninglesscharacters.com/rmc-dsi/
# appurl: https://archive.org/download/rmc-dsi_v2/
# if CDN goes all silly skibidi style
releaseurl: https://cdn.randommeaninglesscharacters.com/assets-dsi/release/
releaseurl_alt: https://cdn.randommeaninglesscharacters.com/releases/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
feed:
  posts_limit: 20