name: rmc
title: rmc
url: https://randommeaninglesscharacters.com
imgurl: https://cdn.randommeaninglesscharacters.com/img-dsi/
appurl: https://cdn.randommeaninglesscharacters.com/rmc-prg/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
feed:
  posts_limit: 20
  # Exclude  all files from `pages` in sitemap











