name: rmc
title: rmc
url: https://randommeaninglesscharacters.com
target: whatever # set to "STRIPPED" for no links version (also unlisted to google)

shopurl: https://shop.randommeaninglesscharacters.com
imgdir: https://cdn.randommeaninglesscharacters.com/dsi-photos/
appdir: https://cdn.randommeaninglesscharacters.com/dsi-devapps/
toolsdir: https://cdn.randommeaninglesscharacters.com/tools/
guidedir: https://cdn.randommeaninglesscharacters.com/guide/
blogdir: https://cdn.randommeaninglesscharacters.com/blog/

imgui: https://cdn.randommeaninglesscharacters.com/ui-images/
# appdir: https://archive.org/download/rmc-dsi_v2/
# if CDN goes all silly skibidi style
releasedir: https://cdn.randommeaninglesscharacters.com/releases/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
feed:
  posts_limit: 20